<?php

namespace Ichinator\NewsBundle\Repository;

/**
 * ForbiddenWordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForbiddenWordsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWords()

    {

        $query = $this->_em->createQuery('SELECT a.word FROM IchinatorNewsBundle:ForbiddenWords a');



        // Utilisation de getSingleResult car la requête ne doit retourner qu'un seul résultat

        return $query->getResult();

    }
}
