imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.burgers_images: /uploads/images/burgers
    app.path.plats_images: /uploads/images/plats
    app.path.desserts_images: /uploads/images/desserts

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "Welcome to BigFood !"
    registration:
            confirmation:
                enabled: true
easy_admin:
    entities:
            User:
                class: AppBundle\Entity\User
                label: 'Utilisateurs'
                list:
                    title: "Utilisateurs de BigFood"
            Burger:
                            class: Ichinator\CommandBundle\Entity\Burger
                            label: 'Les burgers'
                            list:
                                title: "Les burgers"
                            form:
                                            fields:
                                                - { property: 'name', label: 'Nom du burger' }
                                                - { property: 'price', label: 'Prix du burger' }
                                                - { property: 'description', label: 'Description' }
                                                - { property: 'imageFile', type: 'file' }
            Plat:
                            class: Ichinator\CommandBundle\Entity\Plat
                            label: 'Les plats'
                            list:
                                title: "Les plats"
                            form:
                                            fields:
                                                - { property: 'name', label: 'Nom du plat' }
                                                - { property: 'price', label: 'Prix du plat' }
                                                - { property: 'description', label: 'Description' }
                                                - { property: 'imageFile', type: 'file' }
            Dessert:
                            class: Ichinator\CommandBundle\Entity\Dessert
                            label: 'Les desserts'
                            list:
                                title: "Les desserts"
                            form:
                                            fields:
                                                - { property: 'name', label: 'Nom du dessert' }
                                                - { property: 'price', label: 'Prix du dessert' }
                                                - { property: 'description', label: 'Description' }
                                                - { property: 'imageFile', type: 'file' }
            Command:
                            class: Ichinator\CommandBundle\Entity\Command
                            label: 'Les commandes'
                            list:
                                title: "Les commandes ( null si champ vide )"
                            form:
                                            fields:
                                                - { property: 'burger', label: 'Burger de la commande' }
                                                - { property: 'plat', label: 'Plat de la commande' }
                                                - { property: 'dessert', label: 'Dessert de la commande' }
                                                - { property: 'date', label: 'Date prévue' }
            contactMessage:
                            class: Ichinator\ContactBundle\Entity\contactMessage
                            label: 'Messages reçus'
                            list:
                                title: "Les messages reçus"
                            form:
                                            fields:
                                                - { property: 'name', label: 'Noms' }
                                                - { property: 'mailAdress', label: 'Adresses mails' }
                                                - { property: 'telephoneNumber', type: 'tel', label: 'Numéros de téléphone' }
                                                - { property: 'message', type: 'text', label: 'Messages' }
    site_name: 'Big Food'
    list:
            actions:
                - { name: 'show', icon: 'search', label: '', title: 'Chercher' }
                - { name: 'edit', icon: 'pencil', label: '', title: 'Editer' }
                - { name: 'delete', icon: 'remove', label: '', title: 'Supprimer' }

# app/config/config.yml
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
                burgers_images:
                    uri_prefix:         '%app.path.burgers_images%'
                    upload_destination: '%kernel.root_dir%/../web/uploads/images/burgers'
                    namer: vich_uploader.namer_uniqid
                plats_images:
                    uri_prefix:         '%app.path.plats_images%'
                    upload_destination: '%kernel.root_dir%/../web/uploads/images/plats'
                    namer: vich_uploader.namer_uniqid
                desserts_images:
                    uri_prefix:         '%app.path.desserts_images%'
                    upload_destination: '%kernel.root_dir%/../web/uploads/images/desserts'
                    namer: vich_uploader.namer_uniqid

