<?php

namespace Ichinator\ContactBundle\Repository;

/**
 * contactMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contactMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
