<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEvjfm9k\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEvjfm9k/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEvjfm9k.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEvjfm9k\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerEvjfm9k\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Evjfm9k',
    'container.build_id' => '73c57206',
    'container.build_time' => 1523727614,
));
