<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTvjo1fe\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTvjo1fe/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTvjo1fe.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTvjo1fe\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTvjo1fe\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Tvjo1fe',
    'container.build_id' => '0e9ed0ba',
    'container.build_time' => 1522355418,
));
